// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEnQXvgr9X484D4yxH9mG0eGLx0-bmcRE',
    appId: '1:435675895879:web:c72db0dc61773f00c7b962',
    messagingSenderId: '435675895879',
    projectId: 'quickmed-b3ac1',
    authDomain: 'quickmed-b3ac1.firebaseapp.com',
    storageBucket: 'quickmed-b3ac1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH6Fu673019542uVx8r4tN-aZ34qAn1Ks',
    appId: '1:435675895879:android:f7bb0219f69d784ec7b962',
    messagingSenderId: '435675895879',
    projectId: 'quickmed-b3ac1',
    storageBucket: 'quickmed-b3ac1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFV52pyQLE1qp2vPPdhRPSeo6N6lQqPsg',
    appId: '1:435675895879:ios:4cf949311df60509c7b962',
    messagingSenderId: '435675895879',
    projectId: 'quickmed-b3ac1',
    storageBucket: 'quickmed-b3ac1.firebasestorage.app',
    iosBundleId: 'com.example.quickmed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFV52pyQLE1qp2vPPdhRPSeo6N6lQqPsg',
    appId: '1:435675895879:ios:4cf949311df60509c7b962',
    messagingSenderId: '435675895879',
    projectId: 'quickmed-b3ac1',
    storageBucket: 'quickmed-b3ac1.firebasestorage.app',
    iosBundleId: 'com.example.quickmed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEnQXvgr9X484D4yxH9mG0eGLx0-bmcRE',
    appId: '1:435675895879:web:08a4845fc1d5ed05c7b962',
    messagingSenderId: '435675895879',
    projectId: 'quickmed-b3ac1',
    authDomain: 'quickmed-b3ac1.firebaseapp.com',
    storageBucket: 'quickmed-b3ac1.firebasestorage.app',
  );

}